// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Oolong = require("../src/Oolong.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Oolong_Internals = require("../src/Oolong_Internals.bs.js");

function serializeState(state) {
  return Oolong_Internals.Url[/* make */0](/* :: */[
              String(state[/* counter */0]),
              /* [] */0
            ], "", "");
}

var program = Oolong.routerProgram(serializeState, "CounterExample");

var counterProgram_000 = /* debugName */program[/* debugName */0];

var counterProgram_001 = /* serializeState */program[/* serializeState */1];

function counterProgram_002(path, _search, _hash) {
  if (path && !path[1]) {
    return /* State */Block.__(0, [/* record */[/* counter */Caml_format.caml_int_of_string(path[0])]]);
  } else {
    return /* State */Block.__(0, [/* record */[/* counter */0]]);
  }
}

function counterProgram_003(routeAction, _state) {
  var match = routeAction[0];
  if (match && !match[1]) {
    return /* State */Block.__(0, [/* record */[/* counter */Caml_format.caml_int_of_string(match[0])]]);
  } else {
    return /* State */Block.__(0, [/* record */[/* counter */0]]);
  }
}

function counterProgram_004(action, state) {
  if (typeof action === "number") {
    if (action !== 0) {
      return /* Push */Block.__(0, [/* record */[/* counter */state[/* counter */0] - 1 | 0]]);
    } else {
      return /* Push */Block.__(0, [/* record */[/* counter */state[/* counter */0] + 1 | 0]]);
    }
  } else {
    return /* Replace */Block.__(2, [/* record */[/* counter */(action[0] << 1)]]);
  }
}

function counterProgram_005(self) {
  return React.createElement("div", undefined, String(self[/* state */0][/* counter */0]), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(self[/* send */1], /* Increment */0);
                    })
                }, "Increment"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(self[/* send */1], /* Decrement */1);
                    })
                }, "Decrement"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(self[/* send */1], /* Double */[self[/* state */0][/* counter */0]]);
                    })
                }, "Double"));
}

var counterProgram_006 = /* subscriptions */program[/* subscriptions */6];

var counterProgram = /* record */[
  counterProgram_000,
  counterProgram_001,
  counterProgram_002,
  counterProgram_003,
  counterProgram_004,
  counterProgram_005,
  counterProgram_006
];

((
  function() {
    var app = document.createElement("div");
    app.id = "app";
    document.body.appendChild(app);
  }()
));

Oolong.run(Caml_option.some(Oolong_Internals.Router[/* hash */4](/* () */0)), counterProgram)((function (view) {
        return ReactDOMRe.renderToElementWithId(view, "app");
      }));

exports.serializeState = serializeState;
exports.program = program;
exports.counterProgram = counterProgram;
/* program Not a pure module */
