// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Debug = require("bs-platform/lib/js/belt_Debug.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Program$ReactLite = require("./Program.bs.js");

Belt_Debug.setupChromeDebugger(/* () */0);

var program = Program$ReactLite.routerProgram("CounterApp");

function app() {
  return /* record */[
          /* debug */program[/* debug */0],
          /* fromRoute */(function (transition) {
              console.log(transition);
              if (typeof transition === "number" || transition.tag) {
                return /* NoUpdate */0;
              } else {
                var route = transition[0];
                console.log(route[/* path */0]);
                var match = route[/* path */0];
                if (match && match[0] === "") {
                  var match$1 = match[1];
                  if (match$1 && !match$1[1]) {
                    return /* Update */[/* record */[/* counter */Caml_format.caml_int_of_string(match$1[0])]];
                  } else {
                    return /* Update */[/* record */[/* counter */0]];
                  }
                } else {
                  return /* Update */[/* record */[/* counter */0]];
                }
              }
            }),
          /* toRoute */program[/* toRoute */2],
          /* update */(function (state) {
              return /* Update */[/* record */[/* counter */state[/* counter */0] + 1 | 0]];
            }),
          /* view */(function (self) {
              return React.createElement("div", undefined, String(self[/* state */0][/* counter */0]), React.createElement("button", {
                              onClick: (function () {
                                  return Curry._1(self[/* send */1], /* () */0);
                                })
                            }, "Increment"));
            })
        ];
}

((
  function() {
    var app = document.createElement("div");
    app.id = "app";
    document.body.appendChild(app);
  }()
));

Program$ReactLite.startup(app(/* () */0), (function (view) {
        return ReactDOMRe.renderToElementWithId(view, "app");
      }));

console.log("started");

exports.program = program;
exports.app = app;
/*  Not a pure module */
