/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const Oolong_InternalsBS = require('./Oolong_Internals.bs');

import {list} from '../src/shims/ReasonPervasives.shim';

// tslint:disable-next-line:interface-over-type-literal
export type RouterAction_t = 
  | { tag: "Push"; value: [list<string>, string, string] }
  | { tag: "Pop"; value: [list<string>, string, string] }
  | { tag: "Replace"; value: [list<string>, string, string] };

// tslint:disable-next-line:max-classes-per-file 
export abstract class Router_t { protected opaque!: any }; /* simulate opaque types */

export const Router_hash: (_1:void) => Router_t = Oolong_InternalsBS.Router[4];

export const Router_memory: (_1:void) => Router_t = Oolong_InternalsBS.Router[5];
