// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Oolong_Program = require("./Oolong_Program.bs.js");

var ReactProgram = 0;

var Route = Oolong_Program.Route;

var Router = Oolong_Program.Router;

var getRoute = Oolong_Program.getRoute;

var defaultRoute = Oolong_Program.defaultRoute;

var fromRouteDefault = Oolong_Program.fromRouteDefault;

var toRouteDefault = Oolong_Program.toRouteDefault;

var updateDefault = Oolong_Program.updateDefault;

var viewDefault = Oolong_Program.viewDefault;

var program = Oolong_Program.program;

var programStateWrapper = Oolong_Program.programStateWrapper;

var loop = Oolong_Program.loop;

var defaultRouter = Oolong_Program.defaultRouter;

var startup = Oolong_Program.startup;

var routerProgram = Oolong_Program.routerProgram;

exports.ReactProgram = ReactProgram;
exports.Route = Route;
exports.Router = Router;
exports.getRoute = getRoute;
exports.defaultRoute = defaultRoute;
exports.fromRouteDefault = fromRouteDefault;
exports.toRouteDefault = toRouteDefault;
exports.updateDefault = updateDefault;
exports.viewDefault = viewDefault;
exports.program = program;
exports.programStateWrapper = programStateWrapper;
exports.loop = loop;
exports.defaultRouter = defaultRouter;
exports.startup = startup;
exports.routerProgram = routerProgram;
/* Oolong_Program Not a pure module */
