// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var BsHistory = require("bs-history/src/BsHistory.bs.js");
var CreateHashHistory = require("history/createHashHistory");
var CreateMemoryHistory = require("history/createMemoryHistory");

function fromHistoryAction(action) {
  if (action !== 4003185) {
    if (action >= 893009402) {
      return /* Push */1;
    } else {
      return /* Replace */3;
    }
  } else {
    return /* Pop */2;
  }
}

var Action = /* module */[/* fromHistoryAction */fromHistoryAction];

function hash() {
  return CreateHashHistory.default({
              basename: ""
            });
}

function memory() {
  return CreateMemoryHistory.default({
              initialEntries: /* array */["/"],
              initialIndex: 0,
              keyLength: 6
            });
}

function listen(callback, router) {
  return BsHistory.listen((function ($$location, action) {
                  var ourAction = fromHistoryAction(action);
                  return Curry._2(callback, $$location, ourAction);
                }))(router);
}

function getCurrent(router) {
  return router.location;
}

exports.Action = Action;
exports.hash = hash;
exports.memory = memory;
exports.listen = listen;
exports.getCurrent = getCurrent;
/* history/createHashHistory Not a pure module */
