// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var CreateHashHistory = require("history/createHashHistory");
var CreateMemoryHistory = require("history/createMemoryHistory");

function hash() {
  return CreateHashHistory.default({
              basename: ""
            });
}

function memory() {
  return CreateMemoryHistory.default({
              initialEntries: /* array */["/"],
              initialIndex: 0,
              keyLength: 6
            });
}

function getCurrent(router) {
  return router.location;
}

exports.hash = hash;
exports.memory = memory;
exports.getCurrent = getCurrent;
/* history/createHashHistory Not a pure module */
